import{useState,useEffect}from'react';import{useParams,Link}from'react-router-dom';import{useTranslation}from'react-i18next';import{Card,Descriptions,Button,Alert,Spin,Typography,Tag,Divider,message,Space,Result,Form,Input}from'antd';import{CopyOutlined,CheckCircleOutlined,ClockCircleOutlined,LockOutlined,MailOutlined}from'@ant-design/icons';import{publicApi}from'../../services/api';import{cnyToUsdt}from'../../utils/format';const{Paragraph}=Typography;
export default function Order(){const{t}=useTranslation();const{orderNo}=useParams();const[order,setOrder]=useState(null);const[cards,setCards]=useState(null);const[loading,setLoading]=useState(true);const[rate,setRate]=useState(7);const[showPin,setShowPin]=useState(false);const[verifying,setVerifying]=useState(false);
useEffect(()=>{publicApi.getPaymentConfig().then(d=>{if(d.exchangeRate)setRate(d.exchangeRate)}).catch(()=>{})},[]);
useEffect(()=>{publicApi.getOrder(orderNo).then(d=>{setOrder(d);setLoading(false)}).catch(()=>setLoading(false))},[orderNo]);
useEffect(()=>{if(!order||order.status!=='pending')return;const t=setInterval(()=>{publicApi.getOrder(orderNo).then(d=>{if(d)setOrder(d)}).catch(()=>{})},5000);return()=>clearInterval(t)},[order,orderNo]);
const verify=async v=>{setVerifying(true);try{const r=await publicApi.lookupOrder({email:v.email,accessPin:v.accessPin});setOrder(r);if(r.cards)setCards(r.cards);setShowPin(false)}catch(e){message.error(e.message)}finally{setVerifying(false)}};
if(loading)return<div style={{display:'flex',justifyContent:'center',alignItems:'center',minHeight:'60vh'}}><Spin size="large"/></div>;
if(!order)return<div style={{maxWidth:500,margin:'80px auto',padding:16}}><Result status="warning" title="Not found" extra={<Link to="/"><Button type="primary">{t('order.back')}</Button></Link>}/></div>;
const sm={pending:{color:'processing',text:t('order.pending')},paid:{color:'success',text:t('order.paid')},cancelled:{color:'default',text:t('order.cancelled')}};const si=sm[order.status]||{color:'default',text:order.status};
return(<div style={{minHeight:'100vh',background:'#f8fafc',padding:24}}><div style={{maxWidth:680,margin:'0 auto'}}><Link to="/" style={{marginBottom:16,display:'inline-block'}}>{t('order.back')}</Link><Card style={{borderRadius:12}}><div style={{textAlign:'center',marginBottom:24}}>{order.status==='paid'?(<><CheckCircleOutlined style={{fontSize:52,color:'#16a34a'}}/><h2 style={{margin:'10px 0 4px',color:'#16a34a'}}>{t('order.paid')}</h2></>):order.status==='pending'?(<><ClockCircleOutlined style={{fontSize:52,color:'#f59e0b'}}/><h2 style={{margin:'10px 0 4px'}}>{t('order.pending')}</h2><p style={{color:'#94a3b8'}}>支付后输入密码查看卡密</p></>):null}</div><Descriptions column={{xs:1,sm:2}} bordered size="small" style={{marginBottom:20}}><Descriptions.Item label={t('order.orderNo')} span={2}><Paragraph copyable style={{margin:0,fontFamily:'monospace'}}>{order.orderNo}</Paragraph></Descriptions.Item><Descriptions.Item label={t('order.amount')}><span style={{fontSize:18,fontWeight:700}}>¥{parseFloat(order.totalAmount).toFixed(2)}</span></Descriptions.Item><Descriptions.Item label="USDT"><span style={{fontWeight:600}}>{cnyToUsdt(order.totalAmount,rate)} USDT</span></Descriptions.Item><Descriptions.Item label={t('order.status')} span={2}><Tag color={si.color}>{si.text}</Tag></Descriptions.Item>{order.paymentMethod&&<Descriptions.Item label={t('order.payMethod')} span={2}>{order.paymentMethod}</Descriptions.Item>}<Descriptions.Item label={t('order.time')} span={2}>{new Date(order.createdAt).toLocaleString('zh-CN')}</Descriptions.Item>{order.paidAt&&<Descriptions.Item label={t('order.payTime')} span={2}>{new Date(order.paidAt).toLocaleString('zh-CN')}</Descriptions.Item>}</Descriptions>
{order.status==='pending'&&(order.paymentMethod==='usdt_trc20'||!order.paymentMethod)?(<Alert type="warning" showIcon message="USDT-TRC20 支付" description={<div style={{marginTop:8}}><p>请转账 <strong style={{fontSize:16,color:'#dc2626'}}>{cnyToUsdt(order.totalAmount,rate)} USDT</strong> 到：</p><Paragraph copyable code style={{wordBreak:'break-all',padding:10,borderRadius:8,background:'#1e293b',color:'#10b981',fontSize:13}}>TRxSampleWalletAddress123456789abcdefgh</Paragraph><p style={{marginTop:8,color:'#94a3b8',fontSize:13}}>网络 <Tag>TRC20</Tag> 到账后自动确认</p></div>} style={{marginBottom:16,borderRadius:10}}/>):order.status==='pending'&&(order.paymentMethod==='alipay'||order.paymentMethod==='wechat')?<Alert type="info" showIcon message={order.paymentMethod==='alipay'?'支付宝支付':'微信支付'} description={<div style={{marginTop:8}}><p>点击下方按钮跳转到支付页面</p><Button type="primary" size="large" onClick={async()=>{try{const r=await publicApi.createPayment({orderNo:order.orderNo,method:order.paymentMethod});window.open(r.url,'_blank')}catch(e){message.error(e.message)}}} style={{borderRadius:10,marginTop:8}}>{order.paymentMethod==='alipay'?'打开支付宝支付':'打开微信支付'}</Button></div>} style={{marginBottom:16,borderRadius:10}}/>:null}
{order.status==='paid'&&!cards&&(<div style={{textAlign:'center',padding:20}}>{showPin?(<Card size="small" title={t('order.verify')} style={{maxWidth:380,margin:'0 auto',textAlign:'left',borderRadius:10}}><Form onFinish={verify} layout="vertical" size="large"><Form.Item name="email" label={t('order.vEmail')} rules={[{required:true,type:'email'}]}><Input prefix={<MailOutlined/>} placeholder="email" style={{borderRadius:8}}/></Form.Item><Form.Item name="accessPin" label={t('order.vPin')} rules={[{required:true,pattern:/^\d{6}$/}]}><Input.Password prefix={<LockOutlined/>} placeholder="6 digits" maxLength={6} style={{borderRadius:8}}/></Form.Item><Button type="primary" htmlType="submit" block loading={verifying} style={{borderRadius:10,height:44}}>{t('order.vBtn')}</Button></Form></Card>):(<Space direction="vertical"><p style={{color:'#94a3b8'}}>{t('order.verifyHint')}</p><Button type="primary" size="large" icon={<LockOutlined/>} onClick={()=>setShowPin(true)} style={{borderRadius:10}}>{t('order.verify')}</Button></Space>)}</div>)}
{cards&&cards.length>0&&(<div><Divider>{t('order.cards')}</Divider>{cards.map((g,i)=>(<Card key={i} size="small" title={<span>{g.productName}<Tag>×{g.quantity}</Tag></span>} style={{marginBottom:10,borderRadius:10}}>{g.cards.map((c,j)=>(<div key={j} style={{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'10px 14px',background:'#f1f5f9',borderRadius:8,marginBottom:6,fontFamily:'monospace',fontSize:13,border:'1px solid #e2e8f0'}}><span style={{wordBreak:'break-all',flex:1,marginRight:8}}>{c}</span><Button type="primary" size="small" icon={<CopyOutlined/>} onClick={()=>{navigator.clipboard.writeText(c);message.success(t('order.copied'))}} style={{borderRadius:6}}>{t('order.copy')}</Button></div>))}</Card>))}<Alert type="success" showIcon message={t('order.saveHint')} style={{borderRadius:10}}/></div>)}</Card></div></div>)}
