import{useState,useEffect}from'react';import{Table,Button,Modal,Form,Select,Input,Tag,message,Card,Space,Statistic,Row,Col,Alert}from'antd';import{PlusOutlined,ReloadOutlined,InboxOutlined}from'@ant-design/icons';import{adminApi}from'../../services/api';const{TextArea}=Input;
export default function Inventory(){const[inv,setInv]=useState([]);const[products,setProducts]=useState([]);const[loading,setLoading]=useState(true);const[open,setOpen]=useState(false);const[sub,setSub]=useState(false);const[fPid,setFPid]=useState(null);const[fStatus,setFStatus]=useState(null);const[form]=Form.useForm();
const load=async()=>{setLoading(true);try{const params={limit:500};if(fPid)params.productId=fPid;if(fStatus)params.status=fStatus;const[i,p]=await Promise.all([adminApi.getInventory(params),adminApi.getProducts({limit:200})]);setInv(i.items||[]);setProducts(p.items||[])}catch(e){message.error('加载失败')}finally{setLoading(false)}};
useEffect(()=>{load()},[fPid,fStatus]);
const stats={total:inv.length,available:inv.filter(i=>i.status==='available').length,sold:inv.filter(i=>i.status==='sold').length};
const doImport=async()=>{try{const v=await form.validateFields();const cards=v.cardText.split('\n').map(l=>l.trim()).filter(l=>l);if(!cards.length)return message.error('请输入卡密');setSub(true);const r=await adminApi.batchImport({productId:v.productId,cards,skipDuplicates:true});const prod=products.find(p=>p.id===v.productId);message.success(`「${prod?.name}」导入 ${r.imported} 条`+(r.skipped>0?`，跳过 ${r.skipped} 条重复`:''));setOpen(false);form.resetFields();load()}catch(e){if(e.message)message.error(e.message)}finally{setSub(false)}};
const st={available:{color:'green',text:'可用'},sold:{color:'red',text:'已售'},reserved:{color:'blue',text:'预占'}};
const cols=[{title:'ID',dataIndex:'id',width:50},{title:'商品',dataIndex:['product','name'],render:t=><Tag color="blue">{t}</Tag>},{title:'哈希',dataIndex:'cardContentHash',render:h=><code style={{fontSize:10,color:'#94a3b8'}}>{h?.substring(0,10)}...</code>},{title:'状态',dataIndex:'status',width:80,render:v=><Tag color={st[v]?.color}>{st[v]?.text}</Tag>},{title:'创建',dataIndex:'createdAt',width:140,render:v=>v?new Date(v).toLocaleString('zh-CN'):'-'},{title:'售出',dataIndex:'soldAt',width:140,render:v=>v?new Date(v).toLocaleString('zh-CN'):'-'}];
const opts=products.map(p=>({label:`${p.name}(¥${p.price})[${p._count?.inventory||0}]`,value:p.id}));
return(<div><Row gutter={16} style={{marginBottom:16}}><Col span={8}><Card size="small" style={{borderRadius:10}}><Statistic title="总库存" value={stats.total} prefix={<InboxOutlined/>}/></Card></Col><Col span={8}><Card size="small" style={{borderRadius:10}}><Statistic title="可用" value={stats.available} valueStyle={{color:'#16a34a'}}/></Card></Col><Col span={8}><Card size="small" style={{borderRadius:10}}><Statistic title="已售" value={stats.sold} valueStyle={{color:'#dc2626'}}/></Card></Col></Row><Card title="库存管理" extra={<Button type="primary" icon={<PlusOutlined/>} onClick={()=>{form.resetFields();setOpen(true)}}>批量导入</Button>} style={{borderRadius:12}}><Space style={{marginBottom:16}} wrap><Select allowClear placeholder="按商品筛选" style={{minWidth:260}} value={fPid} onChange={setFPid} options={opts} showSearch optionFilterProp="label"/><Select allowClear placeholder="状态" style={{width:110}} value={fStatus} onChange={setFStatus} options={[{label:'可用',value:'available'},{label:'已售',value:'sold'}]}/><Button icon={<ReloadOutlined/>} onClick={load}>刷新</Button></Space><Table columns={cols} dataSource={inv} rowKey="id" loading={loading} size="small" pagination={{pageSize:50,showTotal:t=>`共 ${t} 条`}}/></Card><Modal title="批量导入卡密" open={open} onCancel={()=>setOpen(false)} onOk={doImport} confirmLoading={sub} width={650}><Alert type="info" showIcon message="每行一条卡密，支持任意格式。系统自动去重，原样加密存储。" style={{marginBottom:16}}/><Form form={form} layout="vertical"><Form.Item name="productId" label="选择商品" rules={[{required:true}]}><Select placeholder="搜索商品..." options={opts} showSearch optionFilterProp="label" size="large"/></Form.Item><Form.Item name="cardText" label="卡密内容" rules={[{required:true}]} extra="每行一条，支持任意格式（账号密码、Cookie、Token、JSON 等）"><TextArea rows={12} placeholder={`user1@fb.com|password123|cookie:xxx\nuser2@fb.com|password456|token:yyy\nc_user=10001;xs=28:abc;fr=1BcDeF\n{"email":"u3@x.com","pass":"p3"}`} style={{fontFamily:'monospace',fontSize:13}}/></Form.Item></Form></Modal></div>)}
