import{useState,useEffect}from'react';import{Table,Button,Tag,Modal,Descriptions,Space,message,Card,Input,Select,Typography,Popconfirm}from'antd';import{EyeOutlined,CloseCircleOutlined,CheckCircleOutlined,CopyOutlined}from'@ant-design/icons';import{adminApi}from'../../services/api';const{Paragraph}=Typography;
const sm={pending:{color:'processing',text:'待支付'},paid:{color:'success',text:'已支付'},cancelled:{color:'default',text:'已取消'}};
export default function Orders(){const[orders,setOrders]=useState([]);const[loading,setLoading]=useState(true);const[open,setOpen]=useState(false);const[detail,setDetail]=useState(null);const[cards,setCards]=useState(null);const[filters,setFilters]=useState({});const[confirming,setConfirming]=useState(null);
const load=async()=>{setLoading(true);try{const p={limit:100,...filters};const d=await adminApi.getOrders(p);setOrders(d.items||[])}catch(e){message.error('加载失败')}finally{setLoading(false)}};
useEffect(()=>{load()},[filters]);
const view=async id=>{try{const d=await adminApi.getOrderDetail(id);setDetail(d.order);setCards(d.cards);setOpen(true)}catch(e){message.error(e.message)}};
const cancel=async id=>{try{await adminApi.cancelOrder(id);message.success('已取消');load()}catch(e){message.error(e.message)}};
const confirm=async id=>{setConfirming(id);try{const r=await adminApi.confirmPayment(id);message.success(r.message);load();if(open&&detail?.id===id)view(id)}catch(e){message.error(e.message)}finally{setConfirming(null)}};
const cols=[{title:'订单号',dataIndex:'orderNo',width:160,render:v=><code style={{fontSize:12}}>{v}</code>},{title:'邮箱',dataIndex:'email',ellipsis:true},{title:'金额',dataIndex:'totalAmount',width:90,render:v=><span style={{fontWeight:600}}>¥{parseFloat(v).toFixed(2)}</span>},{title:'状态',dataIndex:'status',width:70,render:v=><Tag color={sm[v]?.color}>{sm[v]?.text}</Tag>},{title:'商品',render:(_,r)=>r.items?.map(i=><Tag key={i.id} color="blue">{i.product?.name} ×{i.quantity}</Tag>)},{title:'时间',dataIndex:'createdAt',width:130,render:v=>new Date(v).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})},{title:'操作',key:'act',width:220,render:(_,r)=><Space size="small"><Button size="small" icon={<EyeOutlined/>} onClick={()=>view(r.id)}>详情</Button>{r.status==='pending'&&<><Popconfirm title="确认支付？库存将立即扣减" onConfirm={()=>confirm(r.id)}><Button size="small" type="primary" icon={<CheckCircleOutlined/>} loading={confirming===r.id}>确认支付</Button></Popconfirm><Button size="small" danger icon={<CloseCircleOutlined/>} onClick={()=>cancel(r.id)}>取消</Button></>}</Space>}];
return(<div><Card title="订单管理" style={{borderRadius:12}}><Space style={{marginBottom:16}} wrap><Select placeholder="状态" allowClear style={{width:110}} value={filters.status} onChange={v=>setFilters({...filters,status:v})} options={[{label:'待支付',value:'pending'},{label:'已支付',value:'paid'},{label:'已取消',value:'cancelled'}]}/><Input.Search placeholder="搜索邮箱/订单号" style={{width:240}} onSearch={v=>setFilters({...filters,email:v,orderNo:v})} allowClear/><Button onClick={load}>刷新</Button></Space><Table columns={cols} dataSource={orders} rowKey="id" loading={loading} size="small"/></Card><Modal title={`订单 ${detail?.orderNo||''}`} open={open} onCancel={()=>{setOpen(false);setDetail(null);setCards(null)}} width={700} footer={detail?.status==='pending'?<Space><Popconfirm title="确认支付？" onConfirm={()=>confirm(detail.id)}><Button type="primary" icon={<CheckCircleOutlined/>} loading={confirming===detail?.id}>确认支付</Button></Popconfirm><Button danger icon={<CloseCircleOutlined/>} onClick={()=>{cancel(detail.id);setOpen(false)}}>取消订单</Button></Space>:null}>{detail&&<><Descriptions column={1} bordered size="small" style={{marginBottom:16}}><Descriptions.Item label="订单号"><Paragraph copyable style={{margin:0}}>{detail.orderNo}</Paragraph></Descriptions.Item><Descriptions.Item label="邮箱">{detail.email}</Descriptions.Item><Descriptions.Item label="金额">¥{parseFloat(detail.totalAmount).toFixed(2)}</Descriptions.Item><Descriptions.Item label="状态"><Tag color={sm[detail.status]?.color}>{sm[detail.status]?.text}</Tag></Descriptions.Item><Descriptions.Item label="支付">{detail.paymentMethod||'-'}</Descriptions.Item><Descriptions.Item label="时间">{new Date(detail.createdAt).toLocaleString('zh-CN')}</Descriptions.Item>{detail.paidAt&&<Descriptions.Item label="支付时间">{new Date(detail.paidAt).toLocaleString('zh-CN')}</Descriptions.Item>}</Descriptions>{detail.status==='paid'&&cards&&cards.length>0&&<div><h4 style={{marginBottom:8,color:'#16a34a'}}>卡密（已解密）</h4>{cards.map((g,i)=>(<Card key={i} size="small" title={`${g.productName} ×${g.quantity}`} style={{marginBottom:8}}>{g.cards.map((c,j)=>(<Paragraph key={j} copyable code style={{margin:'4px 0',padding:8,background:'#f1f5f9',borderRadius:6,fontFamily:'monospace',fontSize:13,whiteSpace:'pre-wrap',wordBreak:'break-all'}}>{c}</Paragraph>))}</Card>))}</div>}{detail.status==='pending'&&<div style={{textAlign:'center',padding:20,color:'#94a3b8'}}>点击「确认支付」模拟支付，查看卡密展示效果</div>}</>}</Modal></div>)}
