import{useState,useEffect}from'react';import{Table,Button,Modal,Form,Input,InputNumber,Select,Space,Tag,Popconfirm,message,Card,Divider}from'antd';import{PlusOutlined,EditOutlined,DeleteOutlined}from'@ant-design/icons';import{adminApi}from'../../services/api';
export default function Products(){const[products,setProducts]=useState([]);const[categories,setCategories]=useState([]);const[loading,setLoading]=useState(true);const[open,setOpen]=useState(false);const[editing,setEditing]=useState(null);const[sub,setSub]=useState(false);const[nCat,setNCat]=useState('');const[addCat,setAddCat]=useState(false);const[form]=Form.useForm();
const load=async()=>{setLoading(true);try{const[p,c]=await Promise.all([adminApi.getProducts({limit:200}),adminApi.getCategories()]);setProducts(p.items||[]);setCategories(c||[])}catch(e){message.error('加载失败')}finally{setLoading(false)}};
useEffect(()=>{load()},[]);
const create=()=>{setEditing(null);form.resetFields();form.setFieldsValue({status:'active',currency:'CNY',sortOrder:0});setNCat('');setOpen(true)};
const edit=r=>{setEditing(r);form.setFieldsValue(r);setNCat('');setOpen(true)};
const del=async id=>{try{await adminApi.deleteProduct(id);message.success('已删除');load()}catch(e){message.error(e.message)}};
const addCategory=async()=>{if(!nCat.trim())return;setAddCat(true);try{const slug=nCat.trim().toLowerCase().replace(/\s+/g,'-');const c=await adminApi.createCategory({name:nCat.trim(),slug});setCategories(p=>[...p,c]);form.setFieldsValue({categoryId:c.id});setNCat('')}catch(e){message.error(e.message)}finally{setAddCat(false)}};
const submit=async()=>{try{const v=await form.validateFields();setSub(true);editing?await adminApi.updateProduct(editing.id,v):await adminApi.createProduct(v);message.success(editing?'已更新':'已创建');setOpen(false);load()}catch(e){if(e.message)message.error(e.message)}finally{setSub(false)}};
const cols=[{title:'ID',dataIndex:'id',width:50},{title:'名称',dataIndex:'name',render:(t,r)=><span>{r.coverImage&&<img src={r.coverImage} style={{width:28,height:28,borderRadius:4,marginRight:8,verticalAlign:'middle'}} alt=""/>}{t}</span>},{title:'分类',dataIndex:['category','name'],render:t=><Tag color="blue">{t}</Tag>},{title:'价格',dataIndex:'price',render:v=><span style={{fontWeight:600}}>¥{parseFloat(v).toFixed(2)}</span>},{title:'库存',render:(_,r)=>{const c=r._count?.inventory||0;return<Tag color={c>0?'green':'red'}>{c} 张</Tag>}},{title:'状态',dataIndex:'status',width:70,render:v=>v==='active'?<Tag color="green">上架</Tag>:<Tag>下架</Tag>},{title:'排序',dataIndex:'sortOrder',width:60},{title:'操作',key:'act',width:140,render:(_,r)=><Space><Button size="small" icon={<EditOutlined/>} onClick={()=>edit(r)}>编辑</Button><Popconfirm title="确定删除？" onConfirm={()=>del(r.id)}><Button size="small" danger icon={<DeleteOutlined/>}/></Popconfirm></Space>}];
return(<div><Card title="商品管理" extra={<Button type="primary" icon={<PlusOutlined/>} onClick={create}>添加商品</Button>} style={{borderRadius:12}}><Table columns={cols} dataSource={products} rowKey="id" loading={loading} size="middle"/></Card><Modal title={editing?'编辑商品':'添加商品'} open={open} onCancel={()=>setOpen(false)} onOk={submit} confirmLoading={sub} width={640}><Form form={form} layout="vertical"><Form.Item name="name" label="名称" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="categoryId" label="分类" rules={[{required:true}]}><Select showSearch optionFilterProp="label" options={categories.map(c=>({label:c.name,value:c.id}))} dropdownRender={m=>(<>{m}<Divider style={{margin:'8px 0'}}/><div style={{display:'flex',padding:'0 8px 4px',gap:8}}><Input placeholder="新分类" value={nCat} onChange={e=>setNCat(e.target.value)} size="small" style={{flex:1}}/><Button type="link" size="small" onClick={addCategory} loading={addCat}>+ 新增</Button></div></>)}/></Form.Item><Form.Item name="description" label="描述"><Input.TextArea rows={3}/></Form.Item><Space style={{display:'flex'}}><Form.Item name="price" label="价格 ¥" rules={[{required:true}]}><InputNumber min={0.01} step={1} precision={2} style={{width:150}}/></Form.Item><Form.Item name="sortOrder" label="排序"><InputNumber min={0} style={{width:80}}/></Form.Item><Form.Item name="status" label="状态"><Select options={[{label:'上架',value:'active'},{label:'下架',value:'inactive'}]} style={{width:90}}/></Form.Item></Space><Form.Item name="coverImage" label="封面图 URL"><Input placeholder="https://..."/></Form.Item></Form></Modal></div>)}
