import { useEffect, useState } from 'react';
import { Alert, Button, Card, Form, Input, InputNumber, Modal, Select, Space, Table, Tag, Typography, message } from 'antd';
import { PlusOutlined, ReloadOutlined, SearchOutlined } from '@ant-design/icons';
import { adminApi } from '../../services/api';

const { Text } = Typography;
const money = (cents) => '¥' + (Number(cents || 0) / 100).toFixed(2);
const labels = { manual_credit: '内部充值', promotional_credit: '活动赠送', support_compensation: '售后补偿', purchase_debit: '订单支付' };

export default function Wallet() {
  const [query, setQuery] = useState(''); const [users, setUsers] = useState([]); const [entries, setEntries] = useState([]); const [selected, setSelected] = useState(null); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(false); const [form] = Form.useForm();
  const loadLedger = async () => { try { const result = await adminApi.getWalletLedger(); setEntries(result.entries || []); } catch (err) { message.error(err.message); } };
  useEffect(() => { loadLedger(); }, []);
  const search = async () => { if (query.trim().length < 2) return message.warning('请输入至少两个字符搜索邮箱'); setLoading(true); try { const result = await adminApi.getWalletUsers({ query: query.trim() }); setUsers(result.items || []); } catch (err) { message.error(err.message); } finally { setLoading(false); } };
  const openCredit = (user) => { setSelected(user); form.resetFields(); form.setFieldsValue({ type: 'manual_credit' }); setOpen(true); };
  const credit = async () => { try { const values = await form.validateFields(); setLoading(true); await adminApi.creditWallet({ userId: selected.id, ...values }); message.success('余额流水已创建'); setOpen(false); await Promise.all([search(), loadLedger()]); } catch (err) { if (err.message) message.error(err.message); } finally { setLoading(false); } };
  const userColumns = [{ title: '用户邮箱', dataIndex: 'email' }, { title: '状态', dataIndex: 'status', width: 90, render: (value) => <Tag color={value === 'active' ? 'green' : 'red'}>{value === 'active' ? '正常' : value}</Tag> }, { title: '余额', dataIndex: 'balanceCents', width: 130, render: (value) => <strong>{money(value)}</strong> }, { title: '注册时间', dataIndex: 'createdAt', width: 180, render: (value) => new Date(value).toLocaleString('zh-CN') }, { title: '操作', width: 120, render: (_, row) => <Button type="primary" size="small" icon={<PlusOutlined />} onClick={() => openCredit(row)}>人工入账</Button> }];
  const ledgerColumns = [{ title: '用户', render: (_, row) => row.user?.email || '-' }, { title: '类型', dataIndex: 'type', render: (value) => <Tag color={value === 'purchase_debit' ? 'orange' : 'green'}>{labels[value] || value}</Tag> }, { title: '金额', dataIndex: 'amountCents', render: (value) => <strong style={{ color: value >= 0 ? '#16a34a' : '#dc2626' }}>{value >= 0 ? '+' : '-'}{money(Math.abs(value))}</strong> }, { title: '余额', dataIndex: 'balanceAfterCents', render: (value) => money(value) }, { title: '订单', render: (_, row) => row.order?.orderNo || '-' }, { title: '管理员', render: (_, row) => row.admin?.username || '系统' }, { title: '时间', dataIndex: 'createdAt', render: (value) => new Date(value).toLocaleString('zh-CN') }];
  return <div><div style={{ marginBottom: 20 }}><Text style={{ display: 'block', fontSize: 22, fontWeight: 800, color: '#0f172a' }}>用户与余额</Text><Text style={{ color: '#64748b' }}>人工入账须验证当前管理员密码，系统只追加不可修改的余额流水。</Text></div><Card style={{ borderRadius: 16, marginBottom: 16 }}><Space wrap><Input value={query} onChange={(event) => setQuery(event.target.value)} onPressEnter={search} prefix={<SearchOutlined />} placeholder="按用户邮箱搜索" style={{ width: 300 }} /><Button type="primary" loading={loading} onClick={search}>搜索用户</Button></Space>{users.length > 0 && <Table style={{ marginTop: 16 }} rowKey="id" columns={userColumns} dataSource={users} pagination={false} scroll={{ x: 700 }} />}</Card><Card title="最近余额流水" extra={<Button icon={<ReloadOutlined />} onClick={loadLedger}>刷新</Button>} style={{ borderRadius: 16 }}><Table rowKey="id" columns={ledgerColumns} dataSource={entries} pagination={{ pageSize: 20 }} scroll={{ x: 900 }} /></Card><Modal title="人工入账" open={open} onCancel={() => setOpen(false)} onOk={credit} confirmLoading={loading} okText="验证密码并入账"><Alert type="warning" showIcon message="本操作会创建不可修改的余额流水。请确认用户、金额和原因无误。" style={{ marginBottom: 16 }} /><Text strong style={{ display: 'block', marginBottom: 12 }}>{selected?.email}，当前余额 {money(selected?.balanceCents)}</Text><Form form={form} layout="vertical"><Form.Item name="amount" label="入账金额（元）" rules={[{ required: true, message: '请输入金额' }]}><InputNumber min={0.01} max={100000} precision={2} style={{ width: '100%' }} /></Form.Item><Form.Item name="type" label="入账类型" rules={[{ required: true }]}><Select options={[{ value: 'manual_credit', label: '内部充值' }, { value: 'promotional_credit', label: '活动赠送' }, { value: 'support_compensation', label: '售后补偿' }]} /></Form.Item><Form.Item name="note" label="原因与备注" rules={[{ required: true, min: 2, max: 300, message: '请填写 2-300 字原因' }]}><Input.TextArea rows={3} /></Form.Item><Form.Item name="password" label="当前管理员密码" rules={[{ required: true, message: '请验证管理员密码' }]}><Input.Password /></Form.Item></Form></Modal></div>;
}
